services:
  web:
    restart: always
    build:
      context: services/backend
      dockerfile: Dockerfile
    container_name: image-hosting-server
    command: ["python", "app.py"]
    env_file:
      - services/backend/.env
    environment:
      - LOG_LEVEL=debug
      - PYTHONPATH=/usr/src/image-hosting-server
    volumes:
      - ./services/backend/src:/usr/src/image-hosting-server
      - ./images:/usr/src/images
      - ./logs:/usr/src/logs
    ports:
      - "8000-8009:8000-8009"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - image-hosting-server-network

  nginx:
    image: nginx:stable-alpine3.21-perl
    container_name: image-hosting-server-nginx
    ports:
      - "80:80"
    volumes:
      - ./images:/usr/src/images:ro
      - ./logs/nginx:/var/log/nginx
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./services/frontend:/usr/share/nginx/html:ro
    depends_on:
      web:
        condition: service_healthy
    networks:
      - image-hosting-server-network

networks:
  image-hosting-server-network: